title: "Scarecrow's Cyber Security Blog"
description: "I like to break stuff and whenever I have time to waste, I hack shit and I talk about it here."

baseurl: "/"
url: "https://scare.rocks"

header_pages:
  - index.md
  - whoami.md
  - doc_list.md
  - blog_list.md

collections:
  blog:
    output: true
  docs:
    output: true
  
footer: 'follow me on <a style="color:red;" href="https://twitter.com/iamscarecrow1">X</a>'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

remote_theme: b2a3e8/jekyll-theme-console
